# Generated by Django 3.2.7 on 2021-10-02 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField()),
                ('updated_by', models.BigIntegerField()),
                ('version', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='studyroom_forum.basemodel')),
                ('description', models.CharField(max_length=1000)),
            ],
            bases=('studyroom_forum.basemodel',),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='studyroom_forum.basemodel')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=1000)),
            ],
            bases=('studyroom_forum.basemodel',),
        ),
        migrations.CreateModel(
            name='QuestionAttachment',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='studyroom_forum.basemodel')),
                ('file_url', models.CharField(max_length=300)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyroom_forum.question')),
            ],
            bases=('studyroom_forum.basemodel',),
        ),
        migrations.CreateModel(
            name='AnswerComments',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='studyroom_forum.basemodel')),
                ('comment', models.CharField(max_length=400)),
                ('answer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyroom_forum.answer')),
            ],
            bases=('studyroom_forum.basemodel',),
        ),
        migrations.CreateModel(
            name='AnswerAttachment',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='studyroom_forum.basemodel')),
                ('file_url', models.CharField(max_length=300)),
                ('answer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyroom_forum.answer')),
            ],
            bases=('studyroom_forum.basemodel',),
        ),
    ]
