# Generated by Django 3.2.7 on 2021-10-04 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studyroom_forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='que_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='studyroom_forum.question'),
            preserve_default=False,
        ),
    ]
