# Generated by Django 3.2.7 on 2021-10-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyroom_forum', '0002_answer_que_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
